"""Structured Day 1 & Day 2 workshop data — source: WorkshopPack registers (2026-06-04)."""

PROVISIONAL_NOTE = "2026-06-04 · Day 1 & Day 2 re-baselined · WorkshopPack SSOT · Phased audience-based delivery (Personal first; foundations end-June, Personal section ~end-July); four-squad resourcing decision"

DECISIONS = [
    ("DEC-001", "Scope", "Migration vs transformation", "Define & bound programme scope: migration, transformation, or hybrid", "Gareth Bew / Keshvi", "Yes - Critical", "Proposed / Open", "Day 2", "D1|S1|SRC-001|Master risk RSK-001"),
    ("DEC-002", "Strategy", "Success metrics", "Platform + customer success metrics (analytics, DS, <3s, NPS, traffic, etc.)", "Gareth Bew", "Confirmed", "Confirmed", "-", "D1|S1|SRC-001|"),
    ("DEC-003", "Scope", "MVP", "MVP = new navigation (4 audiences) + secure web IA", "Gareth Bew / Keshvi", "Confirmed", "Confirmed", "-", "D1|S1|SRC-001|QST-004"),
    ("DEC-004", "Delivery", "Migration dependencies", "Identify & communicate dependencies + tasks per business area", "Programme", "Confirmed (intent)", "Confirmed (intent)", "-", "D1|S1|SRC-001|ACT-002"),
    ("DEC-005", "Delivery", "Whiteboard -> plan", "Per-workstream whiteboard → programme plan + RAID", "Gareth Bew", "Confirmed", "Confirmed", "-", "D1|S1|SRC-001|"),
    ("DEC-006", "Design", "Design foundations", "IA, navigation, templates, content/SEO/brand standards", "Design / OMDS", "Confirmed", "Confirmed", "-", "D1|S1|SRC-001|"),
    ("DEC-007", "Governance", "Handover governance", "Approval routing & entry/exit gates between teams", "Design / Programme", "Yes", "Proposed", "Not confirmed", "D1|S1|SRC-001|ACT-006"),
    ("DEC-008", "Design", "Page treatment", "Product pages → new templates; others as-is/restyled", "Design / Execution", "Yes", "Proposed", "Not confirmed", "D1|S1|SRC-001|QST-002"),
    ("DEC-009", "Technical", "Automated testing", "Automated testing + DevOps pipeline enforcement", "Execution", "Yes", "Proposed", "Not confirmed", "D1|S1|SRC-002|RSK-006"),
    ("DEC-010", "Resourcing", "Dedicated publisher", "Ring-fence dedicated migration publisher from BAU", "Publishing / Programme", "Yes", "Proposed", "Not confirmed", "D1|S1|SRC-001|ACT-003"),
    ("DEC-011", "SEO", "SEO lead time", "SEO team ≥2 months before QA for tagging & validation", "SEO / Programme", "Confirmed (intent)", "Confirmed (intent)", "-", "D1|S1|SRC-001|DEP-009"),
    ("DEC-012", "Migration", "Phased decommissioning", "Turn off legacy components progressively as migrated", "Programme / Execution", "Yes", "Proposed", "Not confirmed", "D1|S2-3|SRC-005|ASM-011"),
    ("DEC-013", "Brand", "Faoli Bank separate brand", "Bank as separate entity with own IA & governance", "Programme", "Yes", "Proposed", "Not confirmed", "D1|S2-3|SRC-005|QST-017"),
    ("DEC-014", "Governance", "Design-phase skip", "Allow some teams to skip design phase (dependency-based)", "Gareth / Brent", "Yes", "Proposed", "Not confirmed", "D1|S2-3|SRC-005|RSK-012"),
    ("DEC-015", "Delivery", "Phased audience-based delivery", "Personal first (foundations end-June, section ~end-July), then Corporate → Business → Wealth (+Secure)", "GB / Programme", "Confirmed", "Confirmed", "-", "D2|S1|SRC-008|DEC-001, QST-016, RSK-031"),
    ("DEC-016", "Resourcing", "Four-squad parallel model", "Four concurrent squads (one per audience): lead designer + designer + content + tech support", "Programme Leadership", "Yes", "Proposed (resource-gated)", "Not confirmed", "D2|S1-2|SRC-008/009|QST-020, ACT-064, RSK-024, TO-7"),
    ("DEC-017", "Design", "Red/green-zone templates", "Modular templates: red zones (fixed/governed) + green zones (variable); 2-3 standardised product templates", "Design / Dev (Seba / Rey)", "Confirmed", "Confirmed", "-", "D2|S1-2|SRC-008/009|TO-8, RSK-025"),
    ("DEC-018", "Design", "Template change-control", "Post-sign-off red-zone changes trigger change management across content + code on all affected pages", "Design / Programme", "Confirmed", "Confirmed", "-", "D2|S1|SRC-008|RSK-025"),
    ("DEC-019", "Governance", "Publishing gatekeeper gate", "Design & publishing teams gatekeep; every page signed off before go-live; only trained builders publish; tenants onboarded to standards", "Design / Publishing (GB / Natalie / Bernice)", "Confirmed", "Confirmed", "-", "D2|S1|SRC-008|DEC-007, RSK-027"),
    ("DEC-020", "Technical", "Content + analytics co-location", "Co-locate content + analytics tagging in Contentstack to enable automation & SEO", "Execution (Rey / Nithin)", "Confirmed", "Confirmed", "-", "D2|S1|SRC-008|ACT-060, RSK-011"),
    ("DEC-021", "Technical", "DevOps quality gates + Playwright", "DevOps quality gates + automated testing (Playwright) + linting before production; rollout end-June with reporting", "Execution", "Confirmed", "Confirmed", "-", "D2|S1|SRC-008|DEC-009"),
    ("DEC-022", "Design", "Personal foundations end-June", "Sign off Personal IA + core templates + generic content guidelines by end-June", "Design (Seba / Justin)", "Confirmed", "Confirmed", "End June", "D2|S1|SRC-008|DEC-006, DEP-017"),
    ("DEC-023", "Design", "Article & news handling", "Single consolidated article page; interim background-colour variant; news distinct (~1-yr retention, stays in footer)", "Design / Content (GB / Justin)", "Confirmed", "Confirmed", "-", "D2|S1|SRC-008|DEC-024, QST-027"),
    ("DEC-024", "Migration", "Defer article/news URL structure", "Defer article/news URL structure pending IA (target end-June); content audit + URL mapping per section as discovery deliverable", "IA / Content (Justin / Bernice)", "Yes", "Deferred", "End June", "D2|S1-2|SRC-008/009|ACT-057, ACT-066, DEP-005"),
    ("DEC-025", "Migration", "Country/site delivery model", "Country teams own migration, depend on central for design/IA/nav/content; South Sudan = decommission-only; SA-first then roll out; small sites quick nav+footer retrofit", "Programme / Regional (GB / Reza)", "Confirmed (intent)", "Confirmed (intent)", "-", "D2|S1|SRC-008|ACT-063, ACT-074, ACT-083"),
    ("DEC-026", "Governance", "Tenant operating model", "Post-migration tenants fund & manage own sites under formal partnership agreements", "Programme (GB / Reza)", "Yes", "Proposed", "Not confirmed", "D2|S1|SRC-008|ACT-080"),
    ("DEC-027", "Governance", "Unified Jira + cadence", "Single Jira construct; leads enter milestones/priorities/deps/confidence; twice-weekly 30-min leadership check-ins + weekly playback", "Programme (GB / Tsoaeli)", "Confirmed", "Confirmed", "-", "D2|S1|SRC-008|ACT-055, ACT-062, ACT-069, ACT-070"),
    ("DEC-028", "Brand", "Bank owns its pages", "Bank builds its own web pages; team involved only on bank-initiated redesign; confirm if OM finance pages move to bank", "Programme", "Confirmed (intent)", "Confirmed (intent)", "-", "D2|S1|SRC-008|DEC-013, QST-021, ACT-076"),
]

TRADEOFFS = [
    ("TO-1", "Scope", "Tactical vs strategic", "Navigation-only vs full transformation", "Gareth Bew / Keshvi", "Choose scope option", "Open", "Day 2", "QST-016, RSK-019"),
    ("TO-2", "Delivery", "Speed vs rework", "Migrate quickly vs wait for foundations", "Programme", "Accept rework risk?", "Open", "Not confirmed", "DEC-008"),
    ("TO-3", "Governance", "Skip design vs full governance", "Direct implementation for some teams", "Gareth / Brent", "Permit skip + criteria?", "Open", "Not confirmed", "DEC-014"),
    ("TO-4", "Design", "Standardisation vs flexibility", "Red zones vs modular green zones / snowflakes", "Brent / OMDS", "Balance standard vs modular", "Open", "Not confirmed", "QST-014"),
    ("TO-5", "Quality", "Quality vs capacity", "Best-practice templates vs available resources", "Programme", "Hold quality despite capacity?", "Open", "Not confirmed", "GB stated quality must not be cut"),
    ("TO-6", "Scope", "Full vs selective migration", "Move all content vs retire low-value pages", "Programme / Execution", "Confirm migration breadth", "Open", "Not confirmed", "ASM-002"),
    ("TO-7", "Resourcing", "Parallel squads vs linear delivery", "Four parallel squads vs current linear capacity", "Programme Leadership", "Approve squad capacity vs accept slip", "Open", "Not confirmed", "DEC-016, RSK-024"),
    ("TO-8", "Design", "Red-zone stability vs green-zone flexibility", "Fixed governed zones vs variable content zones", "Design / Dev", "Balance stability vs flexibility", "Open", "Not confirmed", "DEC-017"),
    ("TO-9", "Scope", "Personal-first focus vs spreading thin", "Focus Personal first vs spread across all segments", "Programme", "Focus vs spread across segments", "Open", "Not confirmed", "DEC-015"),
]

ACTIONS = [
    (1, "All", "Programme", "Critical", "Resolve & document scope decision (migration vs transformation vs hybrid)", "Gareth Bew / Keshvi", "Day 2", "Open", "DEC-001, RSK-001", "D1|S1|SRC-001"),
    (2, "All", "Programme", "Critical", "Define & communicate migration tasks per business area & country", "Programme", "Not confirmed", "Open", "DEC-004, QST-007", "D1|S1|SRC-001"),
    (3, "OMAR / SA", "Publishing", "Critical", "Confirm dedicated OMAR publishing resource; ring-fence BAU", "Bernice Bryce / Programme", "Not confirmed", "Open", "DEC-010, RSK-002", "D1|S1|SRC-002"),
    (4, "All", "Design / Programme", "Critical", "Define & approve 'as-is' migration definition", "Programme / Design", "Not confirmed", "Open", "QST-002, RSK-003", "D1|S1|SRC-002"),
    (5, "OMAR", "Publishing", "High", "Complete page inventory + publishing tracker (vs 1,530 baseline)", "Natalie Patel", "Not confirmed", "In Progress", "RSK-002", "D1|S1|SRC-002"),
    (6, "Design Systems", "OMDS", "High", "Formalise OMDS operating model, design authority, SLAs", "Brent Van Ziller", "Not confirmed", "Open", "DEC-006, DEC-007", "D1|S1|SRC-002"),
    (7, "Design Systems", "OMDS", "High", "Define component lifecycle + impact register", "Brent Van Ziller", "Not confirmed", "Open", "RSK-012", "D1|S1|SRC-002"),
    (8, "All", "Execution", "High", "Figma & DS component audit (existing / reusable / to-build)", "Execution / Design", "Not confirmed", "Open", "DEP-004, RSK-008", "D1|S1|SRC-002"),
    (9, "All", "Execution", "High", "Beta/Staging/Production environment strategy & ownership", "Execution", "Not confirmed", "Open", "QST-006, RSK-010", "D1|S1|SRC-002"),
    (10, "All", "Execution", "Medium", "Add automated testing + DevOps quality gates", "Execution", "Not confirmed", "Open", "DEC-009, RSK-006", "D1|S1|SRC-002"),
    (11, "All", "Execution", "Medium", "Define observability (Dynatrace, Grafana, analytics tagging)", "Execution", "Not confirmed", "Open", "RSK-011", "D1|S1|SRC-002"),
    (12, "All", "SEO", "High", "SEO & analytics workshop — ownership, tooling, tagging standards", "Programme / SEO", "Not confirmed", "Open", "DEC-011, RSK-009", "D1|S1|SRC-002"),
    (13, "All", "Programme", "High", "Go-live readiness checklist (PGW, QAG, ServiceNow, security, comms)", "Programme", "Not confirmed", "Open", "RSK-013", "D1|S1|SRC-002"),
    (14, "Regional", "Programme", "High", "Resource review; confirm regional delivery capacity", "Programme", "Not confirmed", "Open", "RSK-005", "D1|S1|SRC-002"),
    (15, "Namibia", "Regional", "High", "Mitigation plans secure web + servicing (Namibia)", "Programme / Regional", "Not confirmed", "Open", "RSK-014", "D1|S1|SRC-002"),
    (16, "Botswana", "Regional", "High", "Recovery plan for remaining 8 of 9 servicing transactions", "Regional", "Not confirmed", "Open", "RSK-015", "D1|S1|SRC-002"),
    (17, "All", "Execution", "Critical", "URL audit — map URLs to new IA; redirects & switch-off", "Natalie Patel / Execution", "Not confirmed", "Open", "DEP-005, RSK-021", "D1|S1|SRC-002"),
    (18, "All", "Product", "Medium", "Use success metrics to prioritise sections (essential vs as-is)", "Programme / Product", "Not confirmed", "Suggested", "DEC-002", "D1|S1|SRC-001"),
    (19, "All", "Content", "High", "Content readiness checklist + asset standards pack", "Content / OMDS", "Not confirmed", "Open", "DEP-006, RSK-016", "D1|S1|SRC-002"),
    (20, "All", "Design", "High", "Assign owners: landing, article, carousel, theming", "Programme / Design", "Not confirmed", "Open", "QST-010, QST-011", "D1|S1|SRC-002"),
    (21, "Cross Channels", "Programme", "High", "Front-end transition plan post-PI2; Web Platform capacity model", "Programme / CC", "Not confirmed", "Open", "RSK-017, DEP-007", "D1|S1|SRC-002"),
    (22, "Cross Channels", "Cross Channels", "High", "Secure interim BA capacity during recruitment", "Cross Channels", "Not confirmed", "Open", "RSK-018", "D1|S1|SRC-002"),
    (23, "Funeral / EasiPlus", "Cross Channels", "High", "Escalate MFC sign-off for EasiPlus (Funeral template)", "Wayne Moodley", "Not confirmed", "Open", "DEP-008", "D1|S1|SRC-002"),
    (24, "Calculators", "Cross Channels", "Medium", "Personal Loans Calculator scope; PI3 calculator ownership", "Wayne Moodley", "Not confirmed", "Open", "QST-012", "D1|S1|SRC-002"),
    (25, "All", "Programme", "Low", "Assign second scribe for documentation", "Participants", "Not confirmed", "Open", "-", "D1|S2-3|SRC-005"),
    (26, "All", "Programme", "High", "Translate whiteboard outputs into detailed Excel plan", "Gareth Bew", "Not confirmed", "Open", "DEC-005", "D1|S2-3|SRC-005"),
    (27, "All", "Programme", "High", "Break migration plan into tasks + parallel streams", "Gareth, Luvuyo", "Not confirmed", "Open", "ACT-002", "D1|S2-3|SRC-005"),
    (28, "All", "Programme", "Critical", "Gap analysis: committed scope vs 5-month deliverables", "Gareth, Keshvi", "Day 2", "Open", "RSK-001, RSK-019", "D1|S2-3|SRC-006"),
    (29, "Cross Channels", "Cross Channels", "Medium", "Wayne & Tebogo prepare & present delivery-plan changes", "Wayne, Tebogo", "Not confirmed", "Open", "-", "D1|S2-3|SRC-005"),
    (30, "All", "Design", "High", "Sequence ideas; draft logical platform roadmap", "Design team", "Not confirmed", "Open", "DEC-005", "D1|S2-3|SRC-005"),
    (31, "All", "Programme", "Medium", "Define standard compliance requirements across BUs", "Gareth Bew", "Not confirmed", "Open", "-", "D1|S2-3|SRC-005"),
    (32, "All", "Programme", "High", "Senior team track features; help define migration scope", "Senior team", "Not confirmed", "Open", "RSK-001", "D1|S2-3|SRC-005"),
    (33, "All", "Design", "High", "Roll out new design templates across foundational pages", "Gareth / Design", "Not confirmed", "Open", "DEC-006", "D1|S2-3|SRC-005"),
    (34, "All", "OMDS", "Medium", "Define standard patterns for platform features", "Gareth / OMDS", "Not confirmed", "Open", "QST-014", "D1|S2-3|SRC-005"),
    (35, "All", "Design", "High", "Clarify governance for design handover (tenant implementations)", "Design & Content", "Not confirmed", "Open", "DEC-007", "D1|S2-3|SRC-005"),
    (36, "All", "Programme", "High", "Migration approach for teams not yet on new platform", "Gareth, Brent", "Not confirmed", "Open", "RSK-012", "D1|S2-3|SRC-005"),
    (37, "All", "Programme", "Medium", "Document decision to allow design-phase skip (criteria)", "Gareth, Brent", "Not confirmed", "Open", "DEC-014", "D1|S2-3|SRC-005"),
    (38, "All", "Design", "High", "Definition of Done for design artifacts (incl. SEO input)", "Gareth, Brent", "Not confirmed", "Open", "DEC-007", "D1|S2-3|SRC-005"),
    (39, "All", "Design", "High", "Outline approval process for design artifacts", "Gareth, Brent", "Not confirmed", "Open", "DEC-007", "D1|S2-3|SRC-005"),
    (40, "All", "Design / SEO", "High", "Clarify copy finalisation + SEO at design→dev handover", "Gareth, SEO", "Not confirmed", "Open", "DEP-009", "D1|S2-3|SRC-005"),
    (41, "All", "Design", "High", "Finalise template structure; hand to build for parallel dev", "Gareth Bew", "Not confirmed", "Open", "DEC-008", "D1|S2-3|SRC-005"),
    (42, "All", "Design", "High", "Non-negotiable rules for category landing-page templates", "Gareth, team", "Not confirmed", "Open", "DEC-006", "D1|S2-3|SRC-005"),
    (43, "Corporate", "Design", "Medium", "Apply template structure to corporate cluster; identify tweaks", "Gareth, team", "Not confirmed", "Open", "-", "D1|S2-3|SRC-005"),
    (44, "All", "Content", "High", "Content audit per section (migrate/consolidate/delete)", "Gareth, Natalie", "Not confirmed", "Open", "ACT-004", "D1|S2-3|SRC-005"),
    (45, "About / Careers", "Design", "Medium", "Review low-traffic pages for consolidation; define stakeholders", "Gareth, participants", "Not confirmed", "Open", "QST-003", "D1|S2-3|SRC-005"),
    (46, "E-commerce", "Cross Channels", "High", "Notify Nthabi of URL changes for GA tracking", "Wayne Moodley", "Not confirmed", "Open", "RSK-021, DEP-013", "D1|S2-3|SRC-005"),
    (47, "All", "Design / Execution", "High", "Tag Figma with DS components; map names to Contentstack", "Gareth, team", "Not confirmed", "Open", "ACT-008", "D1|S2-3|SRC-005"),
    (48, "All", "OMDS", "Medium", "Align definitions: compositions/components/patterns/templates", "Gareth, team", "Not confirmed", "Open", "QST-014", "D1|S2-3|SRC-005"),
    (49, "OMAR", "Programme", "High", "Re-engage OMAR team; confirm scope & partnership mgmt", "Megan", "Not confirmed", "Open", "QST-013", "D1|S2-3|SRC-005"),
    (50, "All", "Execution", "High", "Automated testing framework; enforce DS in DevOps pipelines", "Gareth, Daniel", "Not confirmed", "Open", "DEC-009", "D1|S2-3|SRC-005"),
    (51, "All", "Execution", "Medium", "Integrate analytics tracking fields in CMS; owner Nithin", "Nithin", "Not confirmed", "Open", "RSK-011", "D1|S2-3|SRC-005"),
    (52, "Calculators", "Cross Channels", "Medium", "Review calculator pages; V2 complete vs additional scope", "Gareth, Wayne", "Not confirmed", "Open", "QST-012", "D1|S2-3|SRC-005"),
    (53, "TFSA", "Cross Channels", "Medium", "Clarify TFSA product page: new template vs existing version", "Gareth, Wayne", "Not confirmed", "Open", "QST-018", "D1|S2-3|SRC-005"),
    (54, "All", "Programme", "High", "Centralised documentation / knowledge system", "Gareth Bew", "Not confirmed", "Open", "RSK-020, ISS-008", "D1|S2-3|SRC-006"),
    (55, "All", "Programme", "High", "Populate shared Roadmap with stream-level work items, owners, milestones, deps & confidence; consolidate & circulate (raw dataset Fri midday)", "Gareth + stream leads", "This week", "Open", "DEC-027, ACT-026", "D2|S1|SRC-008"),
    (56, "Personal", "Content", "High", "Deliver Personal content package (content + QA) so pages/templates are build-ready", "Bernice / Content", "End July", "Open", "DEC-015, DEP-021", "D2|S1|SRC-008"),
    (57, "All", "Content / IA", "High", "Map current article/site URL structure & propose consolidated structure (/articles; news-vs-articles rules)", "Justin, Bernice", "End June", "Open", "DEC-024, ACT-017", "D2|S1|SRC-008"),
    (58, "Personal", "Publishing", "High", "Migrate ~140-150 Personal article pages to new structure once URL structure & packages ready", "Bernice", "June", "Open", "DEC-023", "D2|S1|SRC-008"),
    (59, "All", "Content / Design", "Medium", "Retrofit 'news' onto the article template & migrate news content", "Bernice / Design", "June", "Open", "DEC-023", "D2|S1|SRC-008"),
    (60, "All", "Execution", "High", "Implement content + analytics co-location automation in Contentstack", "Rey, Nithin", "June", "Open", "DEC-020, RSK-011", "D2|S1|SRC-008"),
    (61, "All", "Execution", "High", "Implement DevOps quality gates + CI/CD checks (test/automation reports, linting); begin reporting", "Gareth, Daniel", "End June", "Open", "DEC-021, RSK-006", "D2|S1|SRC-008"),
    (62, "All", "Programme", "Medium", "Set up workstream-lead cadence (twice-weekly 30-min) + weekly playback; circulate invite", "Gareth", "This week", "Open", "DEC-027", "D2|S1|SRC-008"),
    (63, "Regional", "Programme / Regional", "High", "Prepare options & rollout approach for country/site migrations (like-for-like vs full template rework) with effort/cost", "Gareth / Regional", "Not confirmed", "Open", "DEC-025", "D2|S1|SRC-008"),
    (64, "All", "Programme", "Critical", "Produce resourced four-squad view (full-squad resourcing plan + immediate hires/onboarding)", "Seba / Programme", "Not confirmed", "Open", "DEC-016, RSK-024", "D2|S1-2|SRC-008/009"),
    (65, "Personal", "Design", "Critical", "Finalise Personal design foundations (IA, core templates, content guidelines, sign-off); prepare buildable templates", "Gareth, Bertus, Design", "End June", "Open", "DEC-022, DEP-017", "D2|S1|SRC-008"),
    (66, "All", "Content", "High", "Conduct comprehensive content audit + URL mapping per section (added/consolidated/rewritten/removed)", "Gareth, Natalie", "Not confirmed", "Open", "DEC-024, ACT-044", "D2|S1|SRC-008"),
    (67, "All", "Programme", "High", "Define onboarding process & deliverables for new team members/tenants joining in June", "Gareth", "June", "Open", "DEC-019, RSK-027", "D2|S1|SRC-008"),
    (68, "All", "Design", "High", "Finalise & hand over four production-ready template sections to dev within 1-2 sprints (incl. content setup)", "Gareth / Design", "≤2 weeks", "Open", "DEC-017, DEP-017", "D2|S1|SRC-008"),
    (69, "All", "Programme", "High", "Integrate all team boards into a single Jira construct for unified tracking", "Tsoaeli", "Not confirmed", "Open", "DEC-027", "D2|S1|SRC-008"),
    (70, "All", "Programme", "High", "Each stream lead enters milestones, priorities, deadlines, confidence & owners into the spreadsheet", "Brent, Zee, Justin (all leads)", "By Fri", "Open", "DEC-027, ACT-055", "D2|S1|SRC-008"),
    (71, "All", "Execution", "Medium", "Include decommissioning tasks in the project plan; coordinate timing by deployment stage", "Nithin", "Not confirmed", "Open", "DEC-012", "D2|S1|SRC-008"),
    (72, "All", "Security", "High", "Clarify pen-test scope for public web (content + journeys) with Nzama", "Gareth", "Not confirmed", "Open", "RSK-022, DEP-019", "D2|S1|SRC-008"),
    (73, "All", "Business / Programme", "High", "Identify business owners for additional journeys (compliments, complaints, unclaimed benefits, IR, corporate unclaimed benefits); assess in/out of scope", "Gareth, Tebogo", "This week", "Open", "ISS-010, QST-022", "D2|S1-2|SRC-008/009"),
    (74, "Regional", "Programme / Regional", "High", "Assess feature/journey completion per country (Kenya confirm; Malawi/South Sudan tasks); sequence migration/publishing by readiness", "Gareth", "Not confirmed", "Open", "DEC-025, ACT-002", "D2|S1|SRC-008"),
    (75, "All", "Design", "High", "Provide desktop Figma output as source of truth for automation; tag Figma → Contentstack", "Gareth / Design", "Not confirmed", "Open", "ACT-047, DEP-022", "D2|S1|SRC-008"),
    (76, "Bank", "Programme", "Medium", "Clarify whether OM finance pages move to the bank; define next steps", "Gareth", "Not confirmed", "Open", "DEC-028, QST-021", "D2|S1|SRC-008"),
    (77, "All", "Design / Content", "Low", "Clarify naming/structure for financial toolkit & news sections (rename financial toolkit)", "Gareth", "Not confirmed", "Open", "QST-023", "D2|S1|SRC-008"),
    (78, "All", "Programme", "High", "Book consolidation time with Bernice (Jun 5) + Friday (Jun 7) leads review to hand over refined outputs", "Gareth, Bertus, Bernice", "Jun 5-7", "Open", "DEC-027, ACT-055", "D2|S1|SRC-008"),
    (79, "Hong Kong", "Regional", "Medium", "Begin Hong Kong YouTube integration testing (June) → go-live (July); OMI testing June; Vallabh review July", "Gareth / OMI / Vallabh", "Jun-Jul", "Open", "PRK-012", "D2|S1|SRC-008"),
    (80, "All", "Programme", "Medium", "Clarify ownership models & formal agreements for migrated tenant sites (business owner + funding)", "Gareth, Reza", "Not confirmed", "Open", "DEC-026", "D2|S1|SRC-008"),
    (81, "All", "Programme", "Medium", "Identify & confirm owners for unclear assets (fund tables, Bulletin); define working model", "Gareth, Reza", "Not confirmed", "Open", "PRK-011", "D2|S1|SRC-008"),
    (82, "All", "Design", "Medium", "Schedule weekly template playback sessions for early technical-team visibility", "Gareth", "Weekly", "Open", "DEC-017", "D2|S1|SRC-008"),
    (83, "Regional", "Programme / Regional", "Medium", "Document the migration process & run a workshop with country teams to align requirements/next steps", "Gareth", "Not confirmed", "Open", "DEC-025", "D2|S1|SRC-008"),
    (84, "All", "Programme", "Low", "Collect written + virtual participant feedback on the two days; capture improvement suggestions", "All participants", "This week", "Open", "-", "D2|S1|SRC-008"),
]

RAID = []
for r in [
    ("RSK-001", "Migration vs transformation scope ambiguity", "Business", "High", "High", "Programme (GB)", "Formal scope decision (ACT-001)", "Day 2", "Open"),
    ("RSK-002", "Publishing capacity insufficient (~1,530 pages, 2 publishers)", "Resource", "High", "High", "Publishing/Programme", "Dedicated OMAR capacity (ACT-003)", "Not confirmed", "Open"),
    ("RSK-003", "'As-is' definition unclear", "Process", "High", "High", "Programme/Design", "Define as-is (ACT-004)", "Not confirmed", "Open"),
    ("RSK-004", "URL audit/redirect handling incomplete", "Technical", "Medium", "High", "Execution", "URL audit (ACT-017)", "Not confirmed", "Open"),
    ("RSK-005", "Regional resources cut", "Resource", "High", "High", "Programme/Regional", "Resource review (ACT-014)", "Not confirmed", "Open"),
    ("RSK-006", "Daniel limited capacity for automation/testing", "Resource", "Medium", "Medium", "Execution", "Automation plan (ACT-010)", "Not confirmed", "Open"),
    ("RSK-007", "OMDS treated as UI library not governance", "Governance", "Medium", "High", "OMDS", "Operating model (ACT-006)", "Not confirmed", "Open"),
    ("RSK-008", "Most components don't exist in Contentstack", "Technical", "High", "High", "Execution/OMDS", "Component audit (ACT-008)", "Not confirmed", "Open"),
    ("RSK-009", "SEO & analytics ownership not finalised", "Governance", "High", "High", "SEO/Programme", "SEO workshop (ACT-012)", "Not confirmed", "Open"),
    ("RSK-010", "Environment sequencing not defined", "Technical", "Medium", "High", "Execution", "Environment strategy (ACT-009)", "Not confirmed", "Open"),
    ("RSK-011", "Observability/analytics tagging added too late", "Technical", "Medium", "Medium", "Execution", "Embed in delivery (ACT-011)", "Not confirmed", "Open"),
    ("RSK-012", "Component sprawl / design debt", "Technical", "Medium", "Medium", "OMDS", "Lifecycle register (ACT-007)", "Not confirmed", "Open"),
    ("RSK-013", "Go-live readiness activities open", "Governance", "High", "High", "Programme", "Readiness checklist (ACT-013)", "Not confirmed", "Open"),
    ("RSK-014", "Secure web migration at risk", "Delivery", "High", "High", "Programme/Regional", "Mitigation plan (ACT-015)", "Not confirmed", "Open"),
    ("RSK-015", "Servicing transactions at risk (BW 1/9)", "Delivery", "High", "High", "Regional", "Botswana recovery (ACT-016)", "Not confirmed", "Open"),
    ("RSK-016", "Unstandardised images/assets", "Process", "Medium", "Medium", "Content/OMDS", "Asset standards (ACT-019)", "Not confirmed", "Open"),
    ("RSK-017", "Front-end resource exit after PI2", "Resource", "High", "High", "CC/Web Platform", "Transition plan (ACT-021)", "End PI2", "Open"),
    ("RSK-018", "BA capacity constrained", "Resource", "High", "Medium", "Cross Channels", "Interim BA (ACT-022)", "Not confirmed", "Open"),
    ("RSK-019", "Full scope ~2027 vs end-Nov window", "Timeline", "High", "High", "Programme (GB)", "Scope options (ACT-028)", "Day 2", "Open"),
    ("RSK-020", "No centralised knowledge system", "People", "High", "Medium", "Programme (GB)", "Documentation system (ACT-054)", "Not confirmed", "Open"),
    ("RSK-021", "~95% URLs changing impacts e-commerce/GA", "Business", "High", "High", "Execution/E-commerce", "URL audit + notify Nthabi (ACT-046)", "Pre go-live", "Open"),
    ("RSK-022", "Security pen-test + ServiceNow not confirmed", "Security", "Medium", "High", "Programme/Security", "Confirm testing (ACT-013)", "Pre go-live", "Open"),
    ("RSK-023", "Key-resource roll-offs — migration/feature team ~Sept 10; most knowledgeable QE August", "Resource", "High", "High", "Programme/CC (Tebogo)", "Accelerate delivery; knowledge transfer; backfill (ACT-064)", "Sept 10 / Aug", "Open"),
    ("RSK-024", "Linear (current-capacity) delivery will not meet year-end; full scope extends well beyond", "Timeline", "High", "High", "Programme (GB)", "Four-squad parallel model + resource decision (DEC-016, ACT-064)", "Year-end", "Open"),
    ("RSK-025", "Post-sign-off red-zone template changes cascade across content + code on all affected pages", "Technical", "Medium", "High", "Design/Execution", "Red/green zones + change control (DEC-017/018)", "Not confirmed", "Open"),
    ("RSK-026", "Single points of failure — only Gareth & Natalie build templates; Bernice overloaded", "Resource", "High", "High", "Programme/Publishing", "Additional capacity + training + onboarding (ACT-064/067)", "Not confirmed", "Open"),
    ("RSK-027", "Governance/template drift without controls (Contentstack ↔ Figma; new tenants)", "Governance", "Medium", "Medium", "Design/OMDS", "Gatekeeper gate + Figma source-of-truth + onboarding (DEC-019, ACT-075)", "Not confirmed", "Open"),
    ("RSK-028", "Stakeholder sign-off delays extend template sign-off (esp. sequential Personal outreach)", "Business", "Medium", "High", "Programme/Business", "Structured engagement; group sign-off by page type (ACT-065, QST-025)", "Not confirmed", "Open"),
    ("RSK-029", "EasiPlus & dependent journeys blocked until Funeral/product pages complete", "Delivery", "Medium", "High", "Cross Channels (Tebogo/Wayne)", "Sequence product pages; escalate (DEP-018, ACT-074)", "Not confirmed", "Open"),
    ("RSK-030", "Secure-web portfolio-view requirements unclear before Sept roll-off → planning blocked", "Delivery", "High", "High", "Secure Web/Migration (Tebogo)", "Clarify portfolio-view scope (QST-024, DEP-020)", "End Sept", "Open"),
    ("RSK-031", "Not all year-end goals will be delivered → sponsor expectation-management required", "Programme", "Medium", "Medium", "Programme (GB)", "Evidence-based scope communication; phased value (DEC-015)", "Year-end", "Open"),
    ("RSK-032", "Country teams without dedicated content/design resources (OMAR) cannot self-migrate", "Resource", "High", "High", "Programme/Regional", "SA-first rollout + central support + squad extension (DEC-025)", "Not confirmed", "Open"),
]:
    RAID.append(("Risk",) + r)

for i in [
    ("ISS-001", "Full Brand/CI not approved (interim only)", "Templates cannot scale confidently", "Design, OMDS, Brand", "Brand/Group Marketing", "CI approval route", "Not confirmed", "Open"),
    ("ISS-002", "No reliable total page count; manual sheet tracking", "Capacity modelling unreliable", "Publishing, Programme", "Publishing", "Inventory + tracker (ACT-005)", "Not confirmed", "Open"),
    ("ISS-003", "Secure web incomplete; no service-tree solution", "Secure journeys cannot fully go live", "CC, Execution, Service", "Programme", "Mitigation (ACT-015)", "Not confirmed", "Open"),
    ("ISS-004", "Botswana servicing: 1 of 9 complete", "Regional go-live at risk", "Regional (BW)", "Regional", "Recovery plan (ACT-016)", "Not confirmed", "Open"),
    ("ISS-005", "Go-live readiness activities open", "Cannot declare go-live readiness", "Programme, Ops", "Programme", "Checklist (ACT-013)", "Not confirmed", "Open"),
    ("ISS-006", "BA on medical leave; recruitment ongoing", "CC requirements slowed", "Cross Channels", "Cross Channels", "Interim BA (ACT-022)", "Not confirmed", "Open"),
    ("ISS-007", "Single person covers all publishing", "Throughput bottleneck now", "Publishing", "Publishing/Programme", "Dedicated capacity (ACT-003)", "Not confirmed", "Open"),
    ("ISS-008", "No centralised knowledge system today", "Delays, repeated work", "All", "Programme (GB)", "Knowledge system (ACT-054)", "Not confirmed", "Open"),
    ("ISS-009", "Current under-resourcing across all workstreams; teams beyond capacity", "Year-end delivery at risk; quality/morale pressure", "All", "Programme Leadership", "Resource allocation decision (ACT-064)", "Not confirmed", "Open"),
    ("ISS-010", "Unclear business ownership for several journeys (compliments, complaints, unclaimed benefits, IR, corporate unclaimed benefits)", "Migration planning blocked for those journeys", "Business teams", "Programme (GB/Tebogo)", "Identify owners + scope (ACT-073)", "Not confirmed", "Open"),
    ("ISS-011", "Portfolio-view dependencies/requirements unclear for Secure Web; aggravated by Sept roll-off", "Secure-web migration planning stalled", "Secure Web/Migration", "Technical teams (Tebogo)", "Requirements clarification (QST-024, DEP-020)", "Not confirmed", "Open"),
]:
    RAID.append(("Issue",) + i)

DEPENDENCIES = [
    ("DEP-001", "Publishing", "Contentstack dev + content/assets/URLs signed off before publishing", "Programme", "Not confirmed", "Publishing & testing slip", "Enforce gates (DEC-007)", "Programme / Steering", "Open"),
    ("DEP-002", "Publishing", "Testing cannot begin until all pages built in Beta", "Programme", "Not confirmed", "Go-live slip", "Track in Basic View", "Programme", "Open"),
    ("DEP-003", "Cross Channel", "DS V2 deployed to Beta (Find an Advisor + templates)", "Brent Van Ziller", "Not confirmed", "Beta readiness blocked", "Component roadmap", "Programme", "Open"),
    ("DEP-004", "Design", "Figma/DS component audit before template scaling", "Execution/Design", "Not confirmed", "Build blocked / rework", "ACT-008", "Programme", "Open"),
    ("DEP-005", "Publishing", "URL audit before switch-off/redirect decisions", "Natalie Patel", "Not confirmed", "Broken journeys, SEO loss", "ACT-017", "Programme", "Open"),
    ("DEP-006", "Publishing", "Content packs + cluster/SME content before sign-off", "Natalie Patel", "Not confirmed", "Publishing blocked", "ACT-019", "Programme", "Open"),
    ("DEP-007", "Cross Channel", "Cross Channels depends on Web Platform for FE from PI2", "Wayne Moodley", "End PI2", "FE velocity drops", "ACT-021", "Programme", "Open"),
    ("DEP-008", "Cross Channel", "EasiPlus depends on Funeral template + MFC sign-off", "Wayne Moodley", "Not confirmed", "EasiPlus blocked", "ACT-023", "Programme", "Open"),
    ("DEP-009", "SEO", "SEO ≥2 months lead before QA", "SEO", "≥2 months pre-QA", "Go-live blocked by SEO", "DEC-011", "Programme", "Open"),
    ("DEP-010", "Cross Channel", "Tax-free & flexi-invest pages link to migrated V2 journeys", "Cross Channels", "Not confirmed", "Journey continuity gaps", "-", "Programme", "Open"),
    ("DEP-011", "Secure Web", "Service tree/dashboard solution for secure web", "Service team", "Not confirmed", "Secure web blocked", "ACT-015", "Programme", "Open"),
    ("DEP-012", "SEO", "Paid Ads URL requirements from Group Marketing", "Group Marketing", "Not confirmed", "URL/analytics rework", "-", "Programme", "Open"),
    ("DEP-013", "E-commerce", "Notify Nthabi of URL changes for GA tracking", "Wayne Moodley", "Pre go-live", "Broken exec reporting", "ACT-046", "Programme", "Open"),
    ("DEP-014", "Cross Channel", "Final advisor flow into beta (Luvuyo)", "Wayne Moodley", "Not confirmed", "Find an Advisor slip", "-", "Programme", "Open"),
    ("DEP-015", "Go-Live", "Security pen-test/crowdsource before go-live", "Security team", "Pre go-live", "Go-live blocked", "ACT-013", "Steering", "Open"),
    ("DEP-016", "Go-Live", "ServiceNow API updates + approvals before prod", "Programme", "Pre go-live", "Prod deployment blocked", "ACT-013", "Steering", "Open"),
    ("DEP-017", "Design", "Personal IA + core templates + content guidelines complete before dev/build", "Design (Seba/Justin)", "End June", "Build cannot proceed", "DEC-022, ACT-065", "Programme", "Open"),
    ("DEP-018", "Cross Channel", "Product pages complete before EasiPlus & dependent sales journeys deploy", "Web (Gareth)", "Not confirmed", "EasiPlus blocked (reaffirms DEP-008)", "ACT-074", "Programme", "Open"),
    ("DEP-019", "Design", "IA sign-off per audience before each downstream stream proceeds (sequential)", "Design / Business", "Sequential per audience", "Downstream streams blocked", "DEC-015", "Programme", "Open"),
    ("DEP-020", "Secure Web", "Secure-web portfolio-view technical requirements before Sept roll-off", "Secure Web", "End Sept", "Roll-off impact; planning blocked", "QST-024, RSK-030", "Programme", "Open"),
    ("DEP-021", "Content", "Template handover cadence (~every 2 weeks) feeds content creation & parallel builds", "Design", "Ongoing", "Content creation blocked", "ACT-056, DEC-017", "Programme", "Open"),
    ("DEP-022", "Execution", "Desktop Figma output (source of truth) for automation & Contentstack mapping", "Design", "Not confirmed", "Automation blocked", "ACT-075", "Programme", "Open"),
]

CRITICAL_PATH = [
    (1, "Confirm scope (migration vs transformation / tactical option)", "Gareth Bew / Keshvi", "-", "Day 2", "Not confirmed", "Y", "DEC-001"),
    (2, "Define 'as-is' + page-treatment rules", "Design / Programme", "1", "Not confirmed", "Not confirmed", "Y", "ACT-004"),
    (3, "Design foundations (IA, navigation, templates, standards)", "Design / OMDS", "1", "Not confirmed", "Not confirmed", "Y", "DEC-006"),
    (4, "DS component audit + build (Nav, Product pages, DS V2)", "Brent / Execution", "3", "Not confirmed", "Not confirmed", "Y", "RSK-008"),
    (5, "URL audit + structure sign-off", "Natalie Patel", "2", "Not confirmed", "Not confirmed", "Y", "ACT-017"),
    (6, "Content readiness + packs + sign-off", "Natalie Patel", "2", "Not confirmed", "Not confirmed", "Y", "DEP-006"),
    (7, "Complete development in Contentstack", "Nithin / Execution", "4", "Not confirmed", "Not confirmed", "Y", "DEP-001"),
    (8, "Publishing in Beta (all pages built)", "Natalie / Publishing", "7", "Not confirmed", "Not confirmed", "Y", "DEP-002"),
    (9, "SEO engagement ≥2 months before QA", "Bernice / SEO", "3", "Not confirmed", "Not confirmed", "Y", "DEP-009"),
    (10, "Testing → Go-live readiness (security, ServiceNow, decommission)", "Programme / Luvuyo", "8", "Not confirmed", "Not confirmed", "Y", "ACT-013"),
    (11, "Design foundations sign-off (Personal IA + core templates)", "Design (Seba / Justin)", "3", "Not confirmed", "End June", "Y", "DEC-022, DEP-017"),
    (12, "Personal templates + content packages ready", "Design / Bernice", "11", "Not confirmed", "End July", "Y", "DEC-015, DEP-021"),
    (13, "Publishing gatekeeper sign-off (all pages)", "Design / Publishing", "12", "Not confirmed", "Not confirmed", "Y", "DEC-019"),
    (14, "DevOps quality gates (Playwright + linting) before prod", "Execution", "13", "Not confirmed", "End June", "Y", "DEC-021"),
    (15, "Personal go-live → Corporate → Business → Wealth (+Secure)", "Programme", "14", "Not confirmed", "End July+", "Y", "DEC-015"),
]

ROADMAP_ROWS = [
    ("SEO Engagement", "Detailed SEO action plan for rest of year", "Luvuyo / Nodalo", "2026-06-08", "2026-06-12", "CMO officer approval", "In Progress", "Kick off 27 May"),
    ("Go Live Readiness", "Security Team Engagement", "Luvuyo", "2026-06-09", "2026-06-09", "CISO Office", "In Progress", "Pen-test options requested"),
    ("OMAR Engagement", "Re-alignment with OMAR teams", "Keshvi / Luvuyo", "2026-06-08", "2026-06-12", "Irene availability", "In Progress", "-"),
    ("Go Live Readiness", "QAG Team Engagement", "Luvuyo", "2026-06-09", "2026-06-09", "QAG Team", "In Progress", "Pen-test options requested"),
    ("Scope Definition", "Resolve migration vs transformation scope", "Gareth Bew / Keshvi", "Day 2", "Not confirmed", "Sponsor / Steering", "Open", "RSK-019"),
    ("Publishing", "Confirm dedicated OMAR publishing + tracker", "Bernice Bryce", "Not confirmed", "Not confirmed", "Capacity decision", "Not started", "RSK-002"),
    ("Design Systems", "OMDS operating model + component audit + DS V2 Beta", "Brent Van Ziller", "Not confirmed", "Not confirmed", "DS capacity", "Not started", "RSK-008"),
    ("URL Audit", "Map all URLs to new-world IA; redirects", "Natalie Patel", "Not confirmed", "Not confirmed", "IA sign-off", "Not started", "ACT-017"),
    ("SEO Workshop", "Confirm SEO/analytics ownership & standards", "Bernice / Programme", "Not confirmed", "Not confirmed", "SEO readiness", "Not started", "ACT-012"),
    ("Go-Live", "Formal readiness checklist + regional recovery", "Keshvi / Programme", "Not confirmed", "Not confirmed", "Multiple streams", "Not started", "ACT-013/015/016"),
    ("Design Foundations", "Personal IA + core templates + content guidelines sign-off", "Design (Seba / Justin)", "2026-06-04", "2026-06-30", "Stakeholder sign-off", "In Progress", "DEC-022, DEP-017"),
    ("Personal Section", "Personal section live (templates + content + publishing)", "Bernice / Design", "2026-07-01", "2026-07-31", "Foundations sign-off", "Not started", "DEC-015"),
    ("Audience Rollout", "Corporate → Business → Wealth (+ Secure) sequence", "Programme", "2026-08-01", "Not confirmed", "Personal complete", "Not started", "DEC-015"),
    ("Resourcing", "Four-squad resourcing decision + onboarding", "Seba / Programme", "2026-06-08", "Not confirmed", "Sponsor capacity approval", "Open", "DEC-016, ACT-064"),
    ("Resource Roll-off", "Migration/feature team roll-off ~Sept 10; QE roll-off August", "Programme / CC (Tebogo)", "2026-08-01", "2026-09-10", "Knowledge transfer + backfill", "Risk", "RSK-023"),
    ("DevOps Quality Gates", "Quality gates + Playwright + linting; initial rollout", "Execution / Daniel", "2026-06-09", "2026-06-30", "Daniel capacity", "In Progress", "DEC-021, RSK-006"),
    ("Hong Kong", "YouTube integration test (June) → go-live (July)", "Gareth / OMI / Vallabh", "2026-06-01", "2026-07-31", "OMI testing", "Not started", "PRK-012, ACT-079"),
]

GOVERNANCE = [
    ("Steering Committee", "Oversight; scope/budget/risk; shutdown & go-live approvals", "Sponsor (TBC)", "Exec sponsors, programme leads", "TBC", "Consolidated RAID, scope options", "Decisions, approvals", "Sponsor / Exec"),
    ("Programme Delivery Sync", "Track delivery, dependencies, blockers", "Gareth Bew", "Stream leads", "Weekly (TBC)", "Basic View, Action Log", "Updated tracker", "Steering"),
    ("OMDS / Design Authority", "Component governance, standards, exceptions", "Brent Van Ziller", "DS, Design, Group Marketing", "TBC", "Component requests", "Approved components", "Head of Design → Programme"),
    ("Design Handover / Exit-Gate", "Definition of Done design→build→publish", "Design & Content leads", "Design, DS, Dev, Publishing", "Per area", "Designs, content packs", "Handover sign-off", "Programme"),
    ("SEO & Analytics Forum", "SEO/analytics ownership, tooling, tagging", "Luvuyo / Bernice", "SEO, Analytics, Execution", "TBC", "SEO action plan", "Tagging standards", "Programme / CMO"),
    ("Go-Live Readiness Review", "Go/no-go; security, ServiceNow, comms, decommission", "Keshvi / Luvuyo", "Execution, Security, Ops, Comms", "Per release", "Readiness checklist", "Go/no-go", "Steering"),
    ("Leadership Check-in & Playback", "Twice-weekly 30-min check-ins + weekly playback via unified Jira construct (DEC-027)", "Gareth Bew / Tsoaeli", "Stream leads", "Twice-weekly + weekly", "Single Jira (milestones, deps, confidence)", "Updated roadmap, blockers, decisions", "Steering"),
]

OVERVIEW_JOURNEYS = [
    ("Personal / Bank", "OM Bank", "Bank / OMF", "Faoli/OM Bank separate brand — own IA & governance (DEC-013); confirm page ownership (QST-017)"),
    ("Personal / Save", "L&S", "PF", "TBC — lead input required"),
    ("Personal / Invest", "Wealth", "Wealth", "Wealth CI may need separate platform/experience (ISS-001)"),
    ("Personal / Funeral", "L&S", "MFC", "EasiPlus depends on Funeral product template + MFC sign-off (DEP-008)"),
    ("Personal / Insure", "OMInsure", "OMInsure / iWYZE", "TBC — lead input required"),
    ("Personal / Rewards", "Rewards", "Rewards", "TBC — lead input required"),
    ("Business / Corporate", "L&S", "Corporate", "Corporate cluster template stress-test (ACT-043)"),
]

STREAM_INPUTS = [
    ("Publishing", "Natalie Patel", "Publishing tracker", "Complete page inventory + capacity model", None, None, None, "Design/dev/content/URLs", "RSK-002", "Low"),
    ("Publishing", "Natalie Patel", "URL audit", "Map current URLs to new IA", None, None, None, "IA approval", "RSK-021", "Medium"),
    ("Design Standards", "Justin Evans", "Discovery", "Analytics, research, stakeholder engagement", None, None, None, "SME availability", "RSK-005", "Medium"),
    ("Design Systems", "Brent Van Ziller", "Component audit", "Figma audit + Contentstack build", None, None, None, "DS capacity", "RSK-008", "Low"),
    ("Execution", "Nithin Ramsaroop", "Environments", "Beta/Staging/Prod strategy", None, None, None, "Architecture decision", "RSK-010", "Medium"),
    ("Execution", "Nithin Ramsaroop", "Automation", "Automated testing + DevOps gates", None, None, None, "Daniel capacity", "RSK-006", "Low"),
    ("Cross Channels", "Wayne Moodley", "EasiPlus", "Funeral template + MFC sign-off", None, None, None, "DEP-008", "RSK-014", "Medium"),
    ("Cross Channels", "Wayne Moodley", "Calculators", "PI2 Beta; PI3 ownership TBC", None, None, None, "Web Platform PI2", "RSK-017", "Medium"),
    ("Go-Live", "Keshvi / Luvuyo", "Readiness", "Checklist: security, ServiceNow, comms", None, None, None, "Multiple", "RSK-013", "Low"),
    ("SEO", "Bernice / Luvuyo", "SEO plan", "Detailed action plan + ≥2mo lead", "2026-06-08", "2026-06-12", "CMO approval", "SEO readiness", "RSK-009", "Medium"),
]

PHASES = [
    ("PH-01", "Workshop Consolidation and Programme Baseline", "Convert workshop outputs into structured delivery controls", "2026-06-04", "2026-06-07", "IN_PROGRESS", "CONFIRMED", "D2|S1|SRC-008|ACT-055, ACT-078"),
    ("PH-02", "Discovery, Audit and Current-State Validation", "Validate current content, URLs, components, environments and ownership", "2026-06-08", "2026-06-21", "NOT_STARTED", "CONFIRMED", "D1|S1|SRC-002|ACT-017, ACT-044"),
    ("PH-03", "Target-State Definition", "Confirm IA, templates, publishing, governance and operating model", "2026-06-17", "2026-06-30", "NOT_STARTED", "CONFIRMED", "D2|S1|SRC-008|DEC-017, DEC-022"),
    ("PH-04", "Build, Configure and Migrate", "Build templates, configure platform paths and migrate prioritised content", "2026-06-24", "2026-09-30", "NOT_STARTED", "INFERRED", "D2|S1|SRC-008|DEC-015, ACT-068"),
    ("PH-05", "Test, Validate and Sign Off", "Prove production readiness through QA, security, content, design and business gates", "2026-07-15", "2026-10-31", "NOT_STARTED", "INFERRED", "D1|S1|SRC-002|ACT-013, RSK-013"),
    ("PH-06", "Launch and Cutover", "Execute controlled go-live, redirect activation, smoke testing and decision capture", "2026-07-31", "2026-11-30", "NOT_STARTED", "INFERRED", "D1|S1|SRC-001|Hard end-November constraint"),
    ("PH-07", "Hypercare and Stabilisation", "Run post-launch control, support triage, monitoring, fixes and exit reporting", "2026-08-01", "2026-12-14", "NOT_STARTED", "INFERRED", "Requirement|Hypercare formal phase"),
]

DELIVERABLES = [
    ("DEL-001", "PH-01", "governance_pmo", "Consolidated workshop output register", "Curated register set covering decisions, actions, RAID, dependencies, questions and parking-lot items", "Programme", "2026-06-04", "2026-06-07", "IN_PROGRESS", "AMBER", "All Day 1/Day 2 registers ingested with trace refs", "Programme sign-off", "WorkshopPack register evidence", "D2|S1|SRC-008|ACT-055"),
    ("DEL-002", "PH-01", "governance_pmo", "Programme WBS and Gantt baseline", "Hierarchical phase/workstream/deliverable/task baseline with owners, dependencies and confidence", "Gareth Bew", "2026-06-04", "2026-06-07", "IN_PROGRESS", "AMBER", "Contains all 7 phases, 11 workstreams and critical-path tasks", "Steering review", "Extraction matrix and critical-path evidence", "D2|S1|SRC-008|ACT-055, ACT-070"),
    ("DEL-003", "PH-02", "content_ia", "URL audit and redirect map", "Current URL inventory mapped to target IA with redirects and switch-off decisions", "Natalie Patel / Execution", "2026-06-08", "2026-06-21", "NOT_STARTED", "AMBER", "All high-risk URLs mapped or gap logged", "IA and SEO approval", "URL audit source evidence", "D1|S1|SRC-002|ACT-017"),
    ("DEL-004", "PH-02", "design_systems", "Component and template audit", "Figma/design-system/component inventory with reusable, to-build and retired component calls", "Brent Van Ziller / Execution", "2026-06-08", "2026-06-21", "NOT_STARTED", "AMBER", "Component gaps linked to build tasks and risks", "Design authority approval", "Design system evidence", "D1|S1|SRC-002|ACT-008"),
    ("DEL-005", "PH-03", "design_systems", "Personal design foundations package", "Personal IA, core templates and generic content guidelines signed off", "Design (Seba / Justin)", "2026-06-04", "2026-06-30", "IN_PROGRESS", "AMBER", "IA, core templates and content guidelines accepted", "Stakeholder sign-off", "Day 2 Personal foundations evidence", "D2|S1|SRC-008|DEC-022"),
    ("DEL-006", "PH-03", "publishing", "Publishing governance and trained-builder gate", "Gatekeeper model for design/publishing approval, tenant standards and trained builders", "Design / Publishing", "2026-06-17", "2026-06-30", "NOT_STARTED", "AMBER", "Gate criteria and trained-builder conditions documented", "Publishing gatekeeper approval", "Day 2 publishing gate evidence", "D2|S1|SRC-008|DEC-019"),
    ("DEL-007", "PH-04", "technical_migration", "DevOps quality gate implementation", "Playwright, linting and CI/CD reporting before production release", "Execution / Daniel", "2026-06-09", "2026-06-30", "IN_PROGRESS", "AMBER", "Automated reports visible and used as release gates", "Execution sign-off", "DevOps quality gate evidence", "D2|S1|SRC-008|DEC-021"),
    ("DEL-008", "PH-04", "content_ia", "Personal content package and article migration", "Content, QA and article/news migration package for Personal section", "Bernice / Content", "2026-07-01", "2026-07-31", "NOT_STARTED", "AMBER", "Personal package ready to publish with QA evidence", "Content and publishing sign-off", "Day 2 Personal content evidence", "D2|S1|SRC-008|ACT-056, ACT-058"),
    ("DEL-009", "PH-04", "technical_migration", "Country and secure-web migration plan", "Country/site rollout options including secure-web dependencies and South Sudan decommission-only path", "Programme / Regional", "2026-06-08", "2026-08-31", "NOT_STARTED", "AMBER", "Country readiness and secure-web blockers logged", "Programme approval", "Country model evidence", "D2|S1|SRC-008|DEC-025, DEP-020"),
    ("DEL-010", "PH-05", "testing_go_live", "Go-live readiness checklist", "PGW, QAG, ServiceNow, security, comms and decommission readiness checklist", "Programme / Luvuyo", "2026-06-09", "2026-10-31", "NOT_STARTED", "AMBER", "All readiness gates have criteria, evidence and owner", "Go/no-go forum approval", "Readiness source evidence", "D1|S1|SRC-002|ACT-013"),
    ("DEL-011", "PH-05", "contact_support", "Contact centre and support readiness pack", "Agent briefing, scripts, surge support, support queue and feedback process", "Programme / Support", "2026-07-01", "2026-10-31", "NOT_STARTED", "AMBER", "Support team briefed and feedback loop active", "Support owner sign-off", "Requirement-derived support readiness", "Requirement|Contact centre readiness"),
    ("DEL-012", "PH-05", "training_adoption", "Training and adoption pack", "CMS editor, SME and contact-centre training materials, attendance and completion evidence", "Programme / Training", "2026-07-01", "2026-10-31", "NOT_STARTED", "AMBER", "Training completion evidence captured", "Training gate approval", "Requirement-derived training readiness", "Requirement|Training as go-live gate"),
    ("DEL-013", "PH-05", "internal_comms", "Internal communications plan", "Executive, staff, owner and team-level launch communications and FAQ plan", "Programme / Comms", "2026-07-01", "2026-10-31", "NOT_STARTED", "AMBER", "Internal audiences and messages approved", "Comms sign-off", "Requirement-derived internal communications", "Requirement|Internal communications"),
    ("DEL-014", "PH-05", "external_comms", "External communications plan", "Customer, partner, marketing, PR and URL-change support communications", "Programme / Marketing", "2026-07-01", "2026-10-31", "NOT_STARTED", "AMBER", "External comms approved for impacted audiences", "Marketing/PR approval", "Requirement-derived external communications", "Requirement|External communications"),
    ("DEL-015", "PH-06", "testing_go_live", "Go-live decision and cutover pack", "Cutover checklist, go-live command centre, smoke testing, redirect activation and decision record", "Programme / Steering", "2026-07-31", "2026-11-30", "NOT_STARTED", "AMBER", "Go/no-go decision captured with evidence", "Steering committee approval", "Go-live readiness evidence", "D1|S1|SRC-001|End-November constraint"),
    ("DEL-016", "PH-07", "hypercare", "Hypercare operating model and exit report", "Daily stand-ups, triage, support queue, monitoring, fixes, exit criteria and lessons learned", "Programme / Support", "2026-08-01", "2026-12-14", "NOT_STARTED", "AMBER", "Exit criteria met or residual risks escalated", "Programme exit approval", "Requirement-derived hypercare controls", "Requirement|Hypercare formal phase"),
]

WBS_TASKS = [
    ("WBS-001", "PH-01", "governance_pmo", "DEL-001", None, "Build extraction-to-execution matrix", "Gareth Bew", "2026-06-04", "2026-06-07", "IN_PROGRESS", "AMBER", 35, "Y", "HIGH", "Every workshop input mapped or logged as gap", "D2|S1|SRC-008|ACT-055", "CONFIRMED"),
    ("WBS-002", "PH-01", "governance_pmo", "DEL-002", None, "Create WBS and Gantt baseline", "Gareth Bew", "2026-06-04", "2026-06-07", "IN_PROGRESS", "AMBER", 25, "Y", "CRITICAL", "All phases/workstreams/deliverables/tasks represented", "D2|S1|SRC-008|ACT-055, ACT-070", "CONFIRMED"),
    ("WBS-003", "PH-01", "governance_pmo", "DEL-002", "WBS-002", "Resolve scope and resource-vs-year-end escalation", "Programme Leadership", "2026-06-04", "2026-06-14", "BLOCKED", "RED", 10, "Y", "CRITICAL", "Sponsor decision recorded or active risk accepted", "D2|S1|SRC-008|DEC-016, RSK-024", "CONFIRMED"),
    ("WBS-004", "PH-02", "content_ia", "DEL-003", None, "Complete URL audit and redirect mapping", "Natalie Patel / Execution", "2026-06-08", "2026-06-21", "NOT_STARTED", "AMBER", 0, "Y", "CRITICAL", "URL map covers current URLs or explicit gaps", "D1|S1|SRC-002|ACT-017", "CONFIRMED"),
    ("WBS-005", "PH-02", "design_systems", "DEL-004", None, "Complete Figma and DS component audit", "Execution / Design", "2026-06-08", "2026-06-21", "NOT_STARTED", "AMBER", 0, "Y", "HIGH", "Reusable/to-build/retire calls documented", "D1|S1|SRC-002|ACT-008", "CONFIRMED"),
    ("WBS-006", "PH-03", "design_systems", "DEL-005", None, "Sign off Personal IA and core templates", "Design (Seba / Justin)", "2026-06-04", "2026-06-30", "IN_PROGRESS", "AMBER", 20, "Y", "CRITICAL", "Personal IA, templates and guidelines approved", "D2|S1|SRC-008|DEC-022", "CONFIRMED"),
    ("WBS-007", "PH-03", "publishing", "DEL-006", None, "Define publishing gatekeeper workflow", "Design / Publishing", "2026-06-17", "2026-06-30", "NOT_STARTED", "AMBER", 0, "Y", "HIGH", "Gatekeeper criteria and trained builder rules documented", "D2|S1|SRC-008|DEC-019", "CONFIRMED"),
    ("WBS-008", "PH-04", "technical_migration", "DEL-007", None, "Implement Playwright, linting and quality gate reports", "Execution / Daniel", "2026-06-09", "2026-06-30", "IN_PROGRESS", "AMBER", 15, "Y", "HIGH", "Quality reports block production release where failed", "D2|S1|SRC-008|DEC-021", "CONFIRMED"),
    ("WBS-009", "PH-04", "content_ia", "DEL-008", "WBS-006", "Prepare Personal content package and QA evidence", "Bernice / Content", "2026-07-01", "2026-07-31", "NOT_STARTED", "AMBER", 0, "Y", "HIGH", "Content package signed off for build/publish", "D2|S1|SRC-008|ACT-056", "CONFIRMED"),
    ("WBS-010", "PH-04", "content_ia", "DEL-008", "WBS-004", "Migrate Personal article/news structure", "Bernice / Design", "2026-07-01", "2026-07-31", "NOT_STARTED", "AMBER", 0, "N", "HIGH", "Article/news structure and migration QA complete", "D2|S1|SRC-008|DEC-023, ACT-058", "CONFIRMED"),
    ("WBS-011", "PH-04", "technical_migration", "DEL-009", None, "Define country and secure-web rollout options", "Programme / Regional", "2026-06-08", "2026-08-31", "NOT_STARTED", "AMBER", 0, "Y", "HIGH", "Country sequencing and secure-web blockers visible", "D2|S1|SRC-008|DEC-025, DEP-020", "CONFIRMED"),
    ("WBS-012", "PH-05", "testing_go_live", "DEL-010", None, "Create readiness gates and go/no-go checklist", "Programme / Luvuyo", "2026-06-09", "2026-10-31", "NOT_STARTED", "AMBER", 0, "Y", "CRITICAL", "All readiness gates have owner, criteria and evidence", "D1|S1|SRC-002|ACT-013", "CONFIRMED"),
    ("WBS-013", "PH-05", "testing_go_live", "DEL-010", "WBS-012", "Confirm security pen-test and ServiceNow release evidence", "Gareth / Nzama", "2026-06-09", "2026-10-31", "NOT_STARTED", "AMBER", 0, "Y", "HIGH", "Security and ServiceNow approvals logged", "D2|S1|SRC-008|ACT-072, RSK-022", "CONFIRMED"),
    ("WBS-014", "PH-05", "contact_support", "DEL-011", "WBS-012", "Prepare contact-centre scripts and support feedback loop", "Programme / Support", "2026-07-01", "2026-10-31", "NOT_STARTED", "AMBER", 0, "N", "HIGH", "Support queue and feedback loop ready for launch", "Requirement|Contact centre readiness", "INFERRED"),
    ("WBS-015", "PH-05", "training_adoption", "DEL-012", "WBS-012", "Prepare and track CMS/contact-centre/SME training", "Programme / Training", "2026-07-01", "2026-10-31", "NOT_STARTED", "AMBER", 0, "N", "HIGH", "Training completion evidence captured", "Requirement|Training as go-live gate", "INFERRED"),
    ("WBS-016", "PH-05", "internal_comms", "DEL-013", "WBS-012", "Approve internal launch communications", "Programme / Comms", "2026-07-01", "2026-10-31", "NOT_STARTED", "AMBER", 0, "N", "MEDIUM", "Executive, staff and owner communications approved", "Requirement|Internal communications", "INFERRED"),
    ("WBS-017", "PH-05", "external_comms", "DEL-014", "WBS-012", "Approve customer and partner communications", "Programme / Marketing", "2026-07-01", "2026-10-31", "NOT_STARTED", "AMBER", 0, "N", "MEDIUM", "External URL/support messaging approved", "Requirement|External communications", "INFERRED"),
    ("WBS-018", "PH-06", "testing_go_live", "DEL-015", "WBS-012", "Run go/no-go meeting and capture decision", "Programme / Steering", "2026-07-31", "2026-11-30", "NOT_STARTED", "AMBER", 0, "Y", "CRITICAL", "Decision recorded with blockers and evidence", "D1|S1|SRC-001|End-November constraint", "INFERRED"),
    ("WBS-019", "PH-06", "publishing", "DEL-015", "WBS-007", "Execute publishing freeze, release window and rollback control", "Publishing / Programme", "2026-07-31", "2026-11-30", "NOT_STARTED", "AMBER", 0, "Y", "HIGH", "Release controls and rollback path confirmed", "D2|S1|SRC-008|DEC-019", "CONFIRMED"),
    ("WBS-020", "PH-07", "hypercare", "DEL-016", "WBS-018", "Operate hypercare daily triage and support queue", "Programme / Support", "2026-08-01", "2026-12-14", "NOT_STARTED", "AMBER", 0, "N", "HIGH", "Daily triage cadence and support queue active", "Requirement|Hypercare formal phase", "INFERRED"),
    ("WBS-021", "PH-07", "hypercare", "DEL-016", "WBS-020", "Complete stabilisation exit report and lessons learned", "Programme / Support", "2026-08-14", "2026-12-14", "NOT_STARTED", "AMBER", 0, "N", "MEDIUM", "Exit criteria met or residual risk accepted", "Requirement|Hypercare exit criteria", "INFERRED"),
]

TASK_DEPENDENCIES = [
    ("WBS-002", "WBS-003", "finish_to_start", 0, "Scope/resource decision informs baseline credibility"),
    ("WBS-004", "WBS-010", "finish_to_start", 0, "Article/news migration depends on URL structure"),
    ("WBS-006", "WBS-009", "finish_to_start", 0, "Personal content package depends on foundations sign-off"),
    ("WBS-006", "WBS-010", "finish_to_start", 0, "Article templates depend on Personal design foundations"),
    ("WBS-007", "WBS-019", "finish_to_start", 0, "Publishing controls must be defined before release windows"),
    ("WBS-012", "WBS-018", "finish_to_start", 0, "Go/no-go depends on readiness checklist"),
    ("WBS-018", "WBS-020", "finish_to_start", 0, "Hypercare starts after launch decision/cutover"),
]

READINESS_GATES = [
    ("RG-001", "Technical readiness", "technical_migration", "DEL-007", "WBS-008", "DevOps quality gates, automated testing, environments and release controls ready", "Quality reports, environment checklist and release gate evidence", "Execution", "IN_PROGRESS", "AMBER", "Production release decision", "DEC-021, RSK-006", "2026-06-30", "D2|S1|SRC-008|DEC-021", "CONFIRMED"),
    ("RG-002", "Content readiness", "content_ia", "DEL-008", "WBS-009", "Content packages, content QA and article migration ready", "Content checklist, QA results and URL mapping", "Content / Bernice", "NOT_STARTED", "AMBER", "Content sign-off", "ACT-056, ACT-058", "2026-07-31", "D2|S1|SRC-008|ACT-056", "CONFIRMED"),
    ("RG-003", "Design readiness", "design_systems", "DEL-005", "WBS-006", "IA, core templates, red/green zones and design QA approved", "Design sign-off and template acceptance evidence", "Design", "IN_PROGRESS", "AMBER", "Design sign-off", "DEC-017, DEC-022", "2026-06-30", "D2|S1|SRC-008|DEC-022", "CONFIRMED"),
    ("RG-004", "Publishing readiness", "publishing", "DEL-006", "WBS-007", "Publishing gatekeeper model, trained builders and release controls ready", "Publishing checklist and trained-builder evidence", "Design / Publishing", "NOT_STARTED", "AMBER", "Publishing gate approval", "DEC-019", "2026-06-30", "D2|S1|SRC-008|DEC-019", "CONFIRMED"),
    ("RG-005", "Training readiness", "training_adoption", "DEL-012", "WBS-015", "CMS editors, SMEs and contact centre have completed required training", "Attendance, completion and materials evidence", "Programme / Training", "NOT_STARTED", "AMBER", "Training gate approval", "Requirement-derived", "2026-10-31", "Requirement|Training as go-live gate", "INFERRED"),
    ("RG-006", "Contact centre readiness", "contact_support", "DEL-011", "WBS-014", "Contact centre briefings, scripts, support queue and feedback loop ready", "Briefing pack, scripts and escalation rules", "Programme / Support", "NOT_STARTED", "AMBER", "Support readiness approval", "ACT-013", "2026-10-31", "Requirement|Contact centre readiness", "INFERRED"),
    ("RG-007", "Communications readiness", "internal_comms", "DEL-013", "WBS-016", "Internal and stakeholder communications ready", "Comms plan, FAQ and audience approvals", "Programme / Comms", "NOT_STARTED", "AMBER", "Internal comms approval", "ACT-013", "2026-10-31", "Requirement|Internal communications", "INFERRED"),
    ("RG-008", "External communications readiness", "external_comms", "DEL-014", "WBS-017", "Customer, partner, marketing and URL-change communications ready", "External comms plan and support messaging", "Programme / Marketing", "NOT_STARTED", "AMBER", "External comms approval", "Requirement-derived", "2026-10-31", "Requirement|External communications", "INFERRED"),
    ("RG-009", "Business sign-off", "governance_pmo", "DEL-015", "WBS-018", "Business and steering approval captured before cutover", "Signed decision record and open blocker log", "Steering Committee", "NOT_STARTED", "AMBER", "Go/no-go decision", "DEC-027", "2026-11-30", "D2|S1|SRC-008|DEC-027", "INFERRED"),
    ("RG-010", "Security readiness", "technical_migration", "DEL-010", "WBS-013", "Pen-test, security validation and ServiceNow approvals complete", "Security and ServiceNow approval evidence", "Gareth / Nzama", "NOT_STARTED", "AMBER", "Security release approval", "ACT-072, RSK-022", "2026-10-31", "D2|S1|SRC-008|ACT-072", "CONFIRMED"),
    ("RG-011", "Hypercare readiness", "hypercare", "DEL-016", "WBS-020", "Hypercare cadence, support queue, triage and exit criteria ready", "Hypercare operating model and exit criteria", "Programme / Support", "NOT_STARTED", "AMBER", "Hypercare entry approval", "Requirement-derived", "2026-11-30", "Requirement|Hypercare formal phase", "INFERRED"),
]

GOVERNANCE_MEETINGS = [
    ("GOV-MTG-001", "STEERING_COMMITTEE", "Steering Committee", "Oversight, scope/budget/risk, shutdown and go-live approvals", "TBC", None, "Sponsor (TBC)", "Consolidated RAID, scope options, readiness score", "Decisions and approvals", "Sponsor / Exec", "D1|S1|SRC-002|Governance"),
    ("GOV-MTG-002", "LEAD_PLANNING", "Workstream Lead Planning Check-in", "Twice-weekly 30-minute constraint and dependency review", "Twice-weekly", None, "Gareth Bew / Tsoaeli", "Single Jira milestones, dependencies, confidence", "Updated blockers and decisions", "Steering", "D2|S1|SRC-008|DEC-027"),
    ("GOV-MTG-003", "PLAYBACK", "Weekly Template Playback", "Template progress playback for early technical visibility", "Weekly", None, "Gareth Bew", "Template progress, risks, decisions", "Technical feedback and actions", "Programme", "D2|S1|SRC-008|ACT-082"),
    ("GOV-MTG-004", "SME_WORKSHOP", "SEO and Analytics Workshop", "Confirm SEO ownership, tooling and tagging standards", "TBC", "2026-06-08", "Luvuyo / Bernice", "SEO action plan", "Tagging standards and owners", "Programme / CMO", "D1|S1|SRC-002|ACT-012"),
    ("GOV-MTG-005", "SIGN_OFF", "Design Handover Exit Gate", "Definition of Done from design to build to publish", "Per area", None, "Design and Content leads", "Designs, content packs, acceptance criteria", "Handover sign-off", "Programme", "D1|S1|SRC-002|DEC-007"),
    ("GOV-MTG-006", "GO_NO_GO", "Go-Live Readiness Review", "Go/no-go review covering security, ServiceNow, comms and decommission", "Per release", None, "Keshvi / Luvuyo", "Readiness gates and blockers", "Go/no-go decision", "Steering", "D1|S1|SRC-002|ACT-013"),
    ("GOV-MTG-007", "HYPERCARE_STANDUP", "Hypercare Daily Stand-up", "Daily triage and support review during hypercare", "Daily during hypercare", None, "Programme / Support", "Issue log, monitoring, support feedback", "Priority fixes and escalations", "Programme", "Requirement|Hypercare formal phase"),
    ("GOV-MTG-008", "DECISION_FORUM", "Resource and Scope Decision Forum", "Resolve four-squad capacity and year-end delivery gap", "As required", None, "Programme Leadership", "RSK-024, DEC-016, options", "Scope/resource decision", "Steering", "D2|S1|SRC-008|DEC-016"),
    ("GOV-MTG-009", "WORKSTREAM_CHECKPOINT", "Workstream Checkpoint", "Weekly workstream status, RAID and dependency checkpoint", "Weekly", None, "Workstream leads", "Status updates, RAID, dependencies", "Updated WBS and status report", "Programme", "Requirement|Weekly workstream review"),
]

EVIDENCE_LINKS = [
    ("DELIVERABLE", "DEL-002", "SUPPORTS", "SRC-008", "D2 delivery re-baseline requires stream-level work items, owners, milestones, dependencies and confidence", "D2|S1|SRC-008|ACT-055", "CONFIRMED"),
    ("TASK", "WBS-004", "SUPPORTS", "SRC-002", "URL audit and redirect mapping called out as critical control", "D1|S1|SRC-002|ACT-017", "CONFIRMED"),
    ("READINESS_GATE", "RG-001", "SUPPORTS", "SRC-008", "DevOps quality gates, Playwright and linting confirmed before production", "D2|S1|SRC-008|DEC-021", "CONFIRMED"),
    ("READINESS_GATE", "RG-006", "INFERRED_FROM", None, "Contact centre readiness is mandated by the master requirement and linked to go-live readiness", "Requirement|Contact centre readiness", "INFERRED"),
    ("GOVERNANCE_MEETING", "GOV-MTG-002", "SUPPORTS", "SRC-008", "Twice-weekly leadership check-ins and weekly playback confirmed", "D2|S1|SRC-008|DEC-027", "CONFIRMED"),
    ("TASK", "WBS-020", "INFERRED_FROM", None, "Hypercare daily operating mode required by the master requirement", "Requirement|Hypercare formal phase", "INFERRED"),
]

from programme_controls_expansion import (
    DELIVERABLES_EXPANSION,
    EVIDENCE_LINKS_EXPANSION,
    GOVERNANCE_MEETING_DATES,
    TASK_DEPENDENCIES_EXPANSION,
    WBS_TASKS_EXPANSION,
)

# Merge baseline programme controls with expansion for full WBS depth
DELIVERABLES = list(DELIVERABLES) + list(DELIVERABLES_EXPANSION)
WBS_TASKS = list(WBS_TASKS) + list(WBS_TASKS_EXPANSION)
TASK_DEPENDENCIES = list(TASK_DEPENDENCIES) + list(TASK_DEPENDENCIES_EXPANSION)
EVIDENCE_LINKS = list(EVIDENCE_LINKS) + list(EVIDENCE_LINKS_EXPANSION)

# Apply provisional scheduled dates to governance meetings
GOVERNANCE_MEETINGS = [
    (
        row[0], row[1], row[2], row[3], row[4],
        GOVERNANCE_MEETING_DATES.get(row[0], row[5]),
        row[6], row[7], row[8], row[9], row[10],
    )
    for row in GOVERNANCE_MEETINGS
]

REGISTER_COUNTS = {
    "decisions": 28, "actions": 84, "risks": 32, "issues": 11,
    "assumptions": 16, "dependencies": 22, "questions": 27, "parking": 15,
    "phases": len(PHASES),
    "deliverables": len(DELIVERABLES),
    "tasks": len(WBS_TASKS),
    "task_dependencies": len(TASK_DEPENDENCIES),
    "readiness_gates": len(READINESS_GATES),
    "governance_meetings": len(GOVERNANCE_MEETINGS),
    "evidence_links": len(EVIDENCE_LINKS),
}
